[project]
name = "aipb-web-d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.28.0",
    "plotly>=5.17.0",
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
]
